#!/usr/bin/env bash

SCOPE="base"

# @param: packages to install
args_system_packages=${1}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

echo "execting '${SCOPE}' installer..."

# update system package archives
sudo apt-get update -qq > /dev/null

# install useful packages for development
sudo apt-get install -qq git > /dev/null

# http://serverfault.com/a/500778
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales

# update system package archives
sudo apt-get install ${args_system_packages} -qq > /dev/null

echo "'${SCOPE}' installer successfully executed!"
