#!/usr/bin/env bash

SCOPE="fish"

# @param: version of fish to install
args_fish_version=${1}

# @param: additional fisherman packages to install
args_fish_fisherman_packages=${2}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

case ${args_fish_version} in
  "-1")
    echo "skipping '${SCOPE}' installer..."
    ;;
  *)
    echo "execting '${SCOPE}' installer..."

    # install dependencies necessary for git installation
    sudo apt-get -qq install software-properties-common curl > /dev/null

    # add ppa for fish
    sudo apt-add-repository -y ppa:fish-shell/release-2 > /dev/null

    # update repository information
    sudo apt-get -qq update > /dev/null

    # install fish
    sudo apt-get -qq install fish > /dev/null

    # install fisherman
    curl -sL get.fisherman.sh | fish > /dev/null
    fish -c "fisher install cmorrell.com edc/bass f4bio/fisher-nvm ${args_fish_fisherman_packages}> /dev/null"

    # set fish as default shell
    sudo sed -i "s/^vagrant.*:\/bin\/bash/vagrant:x:1000:1000::\/home\/vagrant:\/usr\/bin\/fish/g" /etc/passwd

    echo "'${SCOPE}' installer successfully executed!"
    ;;
esac
