#!/usr/bin/env bash

SCOPE="git"

# @param: version of git to install
args_git_version=${1}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

case ${args_git_version} in
  "-1")
    echo "skipping '${SCOPE}' installer..."
    ;;
  *)
    echo "execting '${SCOPE}' installer..."

    # install dependencies necessary for git installation
    sudo apt-get -qq install software-properties-common > /dev/null

    # add ppa for git
    sudo apt-add-repository -y ppa:git-core/ppa > /dev/null

    # update repository information
    sudo apt-get -qq update > /dev/null

    # install git
    sudo apt-get -qq install git > /dev/null

    echo "'${SCOPE}' installer successfully executed!"
    ;;
esac
