#!/usr/bin/env bash

SCOPE="mysql"

# @param: version of mysql to install
args_mysql_version=${1}

# @param: name of the DB
args_db_name=${2}

# @param: name of the DB
args_db_name=${3}

# @param: username of the DB user
args_db_user=${4}

# @param: password of the DB user
args_db_pass=${5}

# @param: allowed hostname
args_db_host=${6}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

case ${args_mysql_version} in
  "-1")
    echo "skipping '${SCOPE}' installer..."
    ;;
  *)
    echo "execting '${SCOPE}' installer..."

    # install MySQL
    sudo -E apt-get install -qq mysql-server > /dev/null

    # create database
    mysql -uroot -e "create database ${args_db_name};" > /dev/null

    # create user, and grant all permissions to new DB
    mysql -uroot -e "grant all privileges on ${args_db_name}.* to '${args_db_user}'@'${args_db_host}' identified by '${args_db_pass}';" > /dev/null

    echo "'${SCOPE}' installer successfully executed!"
    ;;
esac
