#!/usr/bin/env bash

SCOPE="npm"

# @param: (optional) location to run ``npm install``
args_install_dir=${1}

# @param: (optional) modules will be located at `~/node_modules<args_node_modules_suffix>`
args_node_modules_suffix=${2}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# NPM is automatically installed by Node,
# so we don't have to handle that here

# if requested, run npm install in the specified directory
if [ ! -z "${args_install_dir}" ]; then
  echo "execting '${SCOPE}' installer..."

  mkdir -p $HOME/node_modules${args_node_modules_suffix}
  mkdir -p ${args_install_dir}/node_modules

  if [ -z $(grep "$HOME/node_modules${args_node_modules_suffix}" /etc/fstab) ]; then
    echo "$HOME/node_modules${args_node_modules_suffix} ${args_install_dir}/node_modules none defaults,bind 0 0" | sudo tee -a /etc/fstab
  fi
  sudo mount --bind $HOME/node_modules${args_node_modules_suffix} ${args_install_dir}/node_modules

  cd ${args_install_dir} && npm install --silent > /dev/null

  echo "'${SCOPE}' installer successfully executed!"
else
  echo "skipping '${SCOPE}' installer..."
fi
